main: fr.dragorn421.armorstandstructs.ArmorStandStructsPlugin
name: ArmorStandStructs
version: 0.1
author: Dragorn421
commands:
 armorstandstructs:
  description: ArmorStandStructs
  usage: /armorstandstructs <convert [hollow?] | minimify | move [struct id] | remove <struct id> | rotate <struct id> <rotation> | spin <struct id> <rotation> <interval>>
  aliases: [smallblocks,sb]