main: fr.dragorn421.armorstandstructs.ArmorStandStructsPlugin
name: ArmorStandStructs
version: 0.1
author: Dragorn421
commands:
 armorstandstructs:
  description: ArmorStandStructs
  usage: /armorstandstructs
  alias: [smallblocks,sb]